update

diff --git a/JLopt b/JLopt
--- a/JLopt
+++ b/JLopt
@@ -37,94 +37,94 @@ skip=false
 for ((i=0;i<$#;i++)) do
 if $skip;then skip=false;continue;fi
 case "${opts[$i]}" in
-   -v)
-   	echo "$versioninfo"
-	exit 0;
-	;;
-   -h)
-	echo "$help"
-	exit 0;
-	;;
-   -rn)
-   	sudo -k /usr/local/JLIVECD/main/JLRefreshNetwork
-   	continue
-   	;;
-   -ra)
-   	mkdir -p "$logdir"
-   	echo "" > "$configfile"
-   	continue
-   	;;
-   -t)
-   	timeout="${opts[$((i+1))]}"
-   	[[ $timeout =~ ^[0-9]+$ ]] || { echo "Bad value for timeout: '$timeout'";exit 1; }
-   	timeout=$(echo $timeout |sed "s/^0*\([1-9]\)/\1/;s/^0*$/0/")
-   	if grep -sq '^timeout=' $configfile;then
-   	    sed -r -i.bak "s/(^timeout=).*/\1$timeout/" $configfile
-   	else
-   	    echo "timeout=$timeout" >> $configfile
-   	fi
-   	skip=true;
-   	continue
-   	;;
-   -t1)
-   	terminal1="${opts[$((i+1))]}"
-   	command -v "$terminal1" >/dev/null 2>&1 || { echo "Invalid terminal command: '$terminal1'" ; exit 1; }
-   	if grep -sq '^terminal1=' $configfile;then
-   	    if [[ $(grep -soP '(?<=^terminal2=).*' $configfile) != $terminal1 ]];then
-   	        sed -r -i.bak "s/(^terminal1=).*/\1$terminal1/" $configfile
-   	    else
-   	        echo "This terminal is already a default terminal."
-   	        exit 1
-   	    fi
-   	else
-   	    if [[ $(grep -soP '(?<=^terminal2=).*' $configfile) != $terminal1 ]];then
-   	        echo "terminal1=$terminal1" >> $configfile
-   	    else
-   	        echo "This terminal is already a default terminal."
-   	        exit 1
-   	    fi
-   	fi
-   	skip=true;
-   	continue
-   	;;
-   -t2)
-   	terminal2="${opts[$((i+1))]}"
-   	command -v "$terminal2" >/dev/null 2>&1 || { echo "Invalid terminal command: '$terminal2'" ; exit 1; }
-   	if grep -sq '^terminal2=' $configfile;then
-   	    if [[ $(grep -soP '(?<=^terminal1=).*' $configfile) != $terminal2 ]];then
-   	        sed -r -i.bak "s/(^terminal2=).*/\1$terminal2/" $configfile
-   	    else
-   	        echo "This terminal is already a default terminal."
-   	        exit 1
-   	    fi
-   	else
-   	    if [[ $(grep -soP '(?<=^terminal1=).*' $configfile) != $terminal2 ]];then
-   	        echo "terminal2=$terminal2" >> $configfile
-   	    else
-   	        echo "This terminal is already a default terminal."
-   	        exit 1
-   	    fi
-   	fi
-   	skip=true;
-   	continue
-   	;;
-   -rt1)
-   	sed -r -i.bak "/^terminal1=.*/d" $configfile
-   	continue
-   	;;
-   -rt2)
-   	sed -r -i.bak "/^terminal2=.*/d" $configfile
-   	continue
-   	;;
-   -rt)
-   	sed -r -i.bak "/^terminal1=.*/d" $configfile
-   	sed -r -i.bak "/^terminal2=.*/d" $configfile
-   	continue
-   	;;
-   *)
-   #other unknown options
-   echo "invalid option: '${opts[$i]}'"
-	exit 1;
-	;;
+   -v|--version)
+       	echo "$versioninfo"
+    	exit 0;
+    	;;
+   -rn|--refresh-network)
+       	sudo -k /usr/local/JLIVECD/main/JLRefreshNetwork
+       	continue
+       	;;
+       -ra|--reset-all)
+       	mkdir -p "$logdir"
+       	echo "" > "$configfile"
+       	continue
+       	;;
+   -t|--timeout)
+       	timeout="${opts[$((i+1))]}"
+       	[[ $timeout =~ ^[0-9]+$ ]] || { echo "Bad value for timeout: '$timeout'";exit 1; }
+       	timeout=$(echo $timeout |sed "s/^0*\([1-9]\)/\1/;s/^0*$/0/")
+       	if grep -sq '^timeout=' $configfile;then
+       	    sed -r -i.bak "s/(^timeout=).*/\1$timeout/" $configfile
+       	else
+       	    echo "timeout=$timeout" >> $configfile
+       	fi
+       	skip=true;
+       	continue
+       	;;
+   -t1|--terminal1)
+       	terminal1="${opts[$((i+1))]}"
+       	command -v "$terminal1" >/dev/null 2>&1 || { echo "Invalid terminal command: '$terminal1'" ; exit 1; }
+       	if grep -sq '^terminal1=' $configfile;then
+       	    if [[ $(grep -soP '(?<=^terminal2=).*' $configfile) != $terminal1 ]];then
+       	        sed -r -i.bak "s/(^terminal1=).*/\1$terminal1/" $configfile
+       	    else
+       	        echo "This terminal is already a default terminal."
+       	        exit 1
+       	    fi
+       	else
+       	    if [[ $(grep -soP '(?<=^terminal2=).*' $configfile) != $terminal1 ]];then
+       	        echo "terminal1=$terminal1" >> $configfile
+       	    else
+       	        echo "This terminal is already a default terminal."
+       	        exit 1
+       	    fi
+       	fi
+       	skip=true;
+       	continue
+       	;;
+   -t2|--terminal2)
+       	terminal2="${opts[$((i+1))]}"
+       	command -v "$terminal2" >/dev/null 2>&1 || { echo "Invalid terminal command: '$terminal2'" ; exit 1; }
+       	if grep -sq '^terminal2=' $configfile;then
+       	    if [[ $(grep -soP '(?<=^terminal1=).*' $configfile) != $terminal2 ]];then
+       	        sed -r -i.bak "s/(^terminal2=).*/\1$terminal2/" $configfile
+       	    else
+       	        echo "This terminal is already a default terminal."
+       	        exit 1
+       	    fi
+       	else
+       	    if [[ $(grep -soP '(?<=^terminal1=).*' $configfile) != $terminal2 ]];then
+       	        echo "terminal2=$terminal2" >> $configfile
+       	    else
+       	        echo "This terminal is already a default terminal."
+       	        exit 1
+       	    fi
+       	fi
+       	skip=true;
+       	continue
+   	    ;;
+    -rt1|--reset-terminal1)
+    	sed -r -i.bak "/^terminal1=.*/d" $configfile
+    	continue
+    	;;
+    -rt2|--reset-terminal2)
+    	sed -r -i.bak "/^terminal2=.*/d" $configfile
+    	continue
+    	;;
+    -rt|--reset-terminal)
+    	sed -r -i.bak "/^terminal1=.*/d" $configfile
+    	sed -r -i.bak "/^terminal2=.*/d" $configfile
+    	continue
+    	;;
+    -h|--help)
+        echo "$help"
+        exit 0;
+        ;;
+    *)
+        echo "$help"
+        echo "invalid option: '${opts[$i]}'"
+        exit 1;
+        ;;
 esac
 done
diff --git a/JLstart b/JLstart
--- a/JLstart
+++ b/JLstart
@@ -11,6 +11,16 @@ mkdir -p "$JL_logdirtmp"
 trap finish EXIT
 trap finish SIGTERM
 
+help="
+******** JLstart ********
+Usage:
+    -ub       ubuntu mode
+    -db       debian mode
+    -h        help menu
+    -v        version info
+See JLopt -h for settings.
+"
+
 live_os=
 while [[ $# > 0 ]]
 do
@@ -25,15 +35,15 @@ do
         	JLopt --version
         	exit 0
             ;;
-        -h|--help|*)
-            echo "Usage:"
-            echo "	  -ub		ubuntu mode"
-            echo "    -db       debian mode"
-            echo "    -h        help menu"
-            echo "    -v		version info"
-            echo "See JLopt -h for other usage."
-            exit 1
+        -h|--help)
+            echo "$help"
+            exit 0
             ;;
+        *)
+            echo "$help"
+            echo "invalid option: '$1'"
+            exit 1
+        	;;
     esac
     shift
 done
