update

diff --git a/JLopt b/JLopt
--- a/JLopt
+++ b/JLopt
@@ -1,7 +1,7 @@
 #!/bin/bash
 project='JLIVECD'
 description='Live CD/DVD customization tool'
-version='2.3.1'
+version='2.3.2'
 bugurl='https://github.com/neurobin/JLIVECD/issues'
 author='Md. Jahidul Hamid <jahidulhamid@yahoo.com>'
 source='https://github.com/neurobin/JLIVECD'
@@ -25,6 +25,7 @@ JLopt [options]
 -ra  : factory reset all.
 -rn  : refresh network. Runs JLRefreshNetwork
 -t   : set timeout
+-crt : set chroot command
 -h   : show help menu.
 "
 
@@ -89,6 +90,13 @@ case "${opts[$i]}" in
         echo "$(grep -iv "^[[:blank:]]*$JL_t2n=" "$JL_configfile")" > "$JL_configfile"
     	continue
     	;;
+    -crt|--chroot)
+        chroot="${opts[$((i+1))]}"
+       	command -v "$chroot" >/dev/null 2>&1 || { echo "Invalid chroot command: '$chroot'" ; exit 1; }
+       	update_prop_val "$JL_crtn" "$chroot" "$JL_configfile"
+       	skip=true;
+        continue
+        ;;
     -h|--help)
         echo "$help"
         exit 0;
