added-xterm-as-an-alternative-terminal

diff --git a/main/custom_desktop b/main/custom_desktop
--- a/main/custom_desktop
+++ b/main/custom_desktop
@@ -141,15 +141,24 @@ fi
 mount --bind /dev/ edit/dev
 echo -e "\n......Preparing the chroot terminal......"
 xhost +
-x-terminal-emulator -e "bash -c \"chroot edit ./prepare\"" || { echo "------Preparing chroot failed-----"; }
-echo -e "\n......Preparation complete! Running chroot terminal...\n......When you are finished, run: exit or simply close the chroot terminal.....\n\n...... run 'cat help' or './help' to get help in chroot terminal......\n"
-x-terminal-emulator -e "bash -c \"chroot ./edit;exec bash\"" || { 
-echo "......Failed to run x-terminal-emulator. Check if x-terminal-emulator link exists and not broken"
+x-terminal-emulator -e "bash -c \"chroot edit ./prepare\"" || {
+echo "------Couldn't run x-terminal-emulator, trying xterm...."
+xterm -e "bash -c \"chroot edit ./prepare\""
+} || {
+echo "------Failed to run xterm. Probably not installed!!"
+}
+echo -e "\n......Running chroot terminal...\n......When you are finished, run: exit or simply close the chroot terminal.....\n\n...... run 'cat help' or './help' to get help in chroot terminal......\n"
+x-terminal-emulator -e "bash -c \"chroot ./edit;bash\"" || {
+echo "------Failed to run x-terminal-emulator. Check if x-terminal-emulator link exists and not broken"
+echo "......Trying xterm....."
+xterm -e "bash -c \"chroot ./edit;bash\"" 
+} || {
+echo "------Failed to run xterm. Probably not installed!!"
 read -e -p "Want to continue without chroot (Y/n)?: " choice1
 if [[ $choice1 =~ [Yy] ]];then
   echo "......Continuing without chroot. No modification will be done"
 else
-  echo "......Running x-terminal-emulator failed. Exiting..."
+  echo "......Counldn't run the chroot terminal, exiting..."
   exit 2
 fi
 }
